#!/bin/bash

# Dotfiles home
export DOTFILES_HOME=${HOME}/.dotfiles

# Android
export ANDROID_SDK_HOME=${HOME}/Android/
export ANDROID_STUDIO_HOME=${HOME}/android-studio/
export ANDROID_PLATFORM_TOOLS=${ANDROID_SDK_HOME}/Sdk/platform-tools/

# Flutter
export FLUTTER_SDK_HOME=${HOME}/flutter/
export FLUTTER_TOOLS="${FLUTTER_SDK_HOME}/bin"

# Images
export WALLPAPERS_HOME=${DOTFILES_HOME}/wallpapers

# Screen layouts
export SCREENLAYOUT_HOME=${DOTFILES_HOME}/screenlayout

# Shorcuts
export SHORTCUTS_HOME=${DOTFILES_HOME}/shortcuts

export PATH=${PATH}:${SHORTCUTS_HOME}:${ANDROID_PLATFORM_TOOLS}:${FLUTTER_TOOLS}

