#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# fixes mouse cursor
xsetroot -cursor_name left_ptr &

# wallpaper
feh --bg-scale $WALLPAPERS_HOME/hollow-knight-nail.jpg 

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
  sh $SCREENLAYOUT_HOME/home.sh
  bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
fi

if [[ $(xrandr -q | grep "DP-1 connected") ]]; then
  sh $SCREENLAYOUT_HOME/office.sh
  bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width          4
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

