#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# fixes mouse cursor
xsetroot -cursor_name left_ptr &

sh $SCRIPTS_HOME/load-monitors.sh

feh --bg-scale $WALLPAPERS_HOME/hollow-knight-nail.jpg &
betterlockscreen -w dim &
source $HOME/.fehbg

bspc config border_width          4
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

