#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width          4
bspc config window_gap            12

bspc config split_ratio           0.5
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Fixes mouse cursor
xsetroot -cursor_name left_ptr

